//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the MolecularCodeGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     The generator code can be found here, in this github repository:
//     https://github.com/Heymity/MolecularLibCore/tree/main/MolecularAutomaticCodeGenerator
// </auto-generated>
//------------------------------------------------------------------------------

namespace MolecularLib
{
    public interface IArgsInstantiable
    {
        public void Initialize();
    }

    public interface IArgsInstantiable<in TArg0>
    {
        public void Initialize(TArg0 arg0);
    }

    public interface IArgsInstantiable<in TArg0, in TArg1>
    {
        public void Initialize(TArg0 arg0, TArg1 arg1);
    }

    public interface IArgsInstantiable<in TArg0, in TArg1, in TArg2>
    {
        public void Initialize(TArg0 arg0, TArg1 arg1, TArg2 arg2);
    }

    public interface IArgsInstantiable<in TArg0, in TArg1, in TArg2, in TArg3>
    {
        public void Initialize(TArg0 arg0, TArg1 arg1, TArg2 arg2, TArg3 arg3);
    }

    public interface IArgsInstantiable<in TArg0, in TArg1, in TArg2, in TArg3, in TArg4>
    {
        public void Initialize(TArg0 arg0, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4);
    }

    public interface IArgsInstantiable<in TArg0, in TArg1, in TArg2, in TArg3, in TArg4, in TArg5>
    {
        public void Initialize(TArg0 arg0, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5);
    }

    public interface IArgsInstantiable<in TArg0, in TArg1, in TArg2, in TArg3, in TArg4, in TArg5, in TArg6>
    {
        public void Initialize(TArg0 arg0, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6);
    }

    public interface IArgsInstantiable<in TArg0, in TArg1, in TArg2, in TArg3, in TArg4, in TArg5, in TArg6, in TArg7>
    {
        public void Initialize(TArg0 arg0, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7);
    }

    public interface IArgsInstantiable<in TArg0, in TArg1, in TArg2, in TArg3, in TArg4, in TArg5, in TArg6, in TArg7, in TArg8>
    {
        public void Initialize(TArg0 arg0, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7, TArg8 arg8);
    }

    public interface IArgsInstantiable<in TArg0, in TArg1, in TArg2, in TArg3, in TArg4, in TArg5, in TArg6, in TArg7, in TArg8, in TArg9>
    {
        public void Initialize(TArg0 arg0, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7, TArg8 arg8, TArg9 arg9);
    }

}
