//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the MolecularCodeGenerator.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     The generator code can be found here, in this github repository:
//     https://github.com/Heymity/MolecularLibCore/tree/main/MolecularAutomaticCodeGenerator
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEngine;

namespace MolecularLib
{
    public static partial class Molecular
    {
        /// <summary>)
        /// Instantiates a Object that derives from IArgsInstantiable with 0 parameters and calls the initialize function
        /// </summary>
        public static T Instantiate<T>(T original) where T : Object, IArgsInstantiable
        {
            var instanceObj = Object.Instantiate(original);

            if (instanceObj is IArgsInstantiable argsInstantiable)
                argsInstantiable.Initialize();

            return instanceObj;
        }

        /// <summary>)
        /// Instantiates a Object that derives from IArgsInstantiable with 0 parameters and calls the initialize function
        /// </summary>
        public static T Instantiate<T>(T original, Transform parent) where T : Object, IArgsInstantiable
        {
            var instanceObj = Object.Instantiate(original, parent);

            if (instanceObj is IArgsInstantiable argsInstantiable)
                argsInstantiable.Initialize();

            return instanceObj;
        }

        /// <summary>)
        /// Instantiates a Object that derives from IArgsInstantiable with 0 parameters and calls the initialize function
        /// </summary>
        public static T Instantiate<T>(T original, Vector3 position, Quaternion rotation) where T : Object, IArgsInstantiable
        {
            var instanceObj = Object.Instantiate(original, position, rotation);

            if (instanceObj is IArgsInstantiable argsInstantiable)
                argsInstantiable.Initialize();

            return instanceObj;
        }

        /// <summary>)
        /// Instantiates a Object that derives from IArgsInstantiable with 0 parameters and calls the initialize function
        /// </summary>
        public static T Instantiate<T>(T original, Vector3 position, Quaternion rotation, Transform parent) where T : Object, IArgsInstantiable
        {
            var instanceObj = Object.Instantiate(original, position, rotation, parent);

            if (instanceObj is IArgsInstantiable argsInstantiable)
                argsInstantiable.Initialize();

            return instanceObj;
        }

        /// <summary>)
        /// Instantiates a Object that derives from IArgsInstantiable with 1 parameters and calls the initialize function
        /// </summary>
        public static T Instantiate<T, TArg0>(T original, TArg0 arg0) where T : Object, IArgsInstantiable<TArg0>
        {
            var instanceObj = Object.Instantiate(original);

            if (instanceObj is IArgsInstantiable<TArg0> argsInstantiable)
                argsInstantiable.Initialize(arg0);

            return instanceObj;
        }

        /// <summary>)
        /// Instantiates a Object that derives from IArgsInstantiable with 1 parameters and calls the initialize function
        /// </summary>
        public static T Instantiate<T, TArg0>(T original, Transform parent, TArg0 arg0) where T : Object, IArgsInstantiable<TArg0>
        {
            var instanceObj = Object.Instantiate(original, parent);

            if (instanceObj is IArgsInstantiable<TArg0> argsInstantiable)
                argsInstantiable.Initialize(arg0);

            return instanceObj;
        }

        /// <summary>)
        /// Instantiates a Object that derives from IArgsInstantiable with 1 parameters and calls the initialize function
        /// </summary>
        public static T Instantiate<T, TArg0>(T original, Vector3 position, Quaternion rotation, TArg0 arg0) where T : Object, IArgsInstantiable<TArg0>
        {
            var instanceObj = Object.Instantiate(original, position, rotation);

            if (instanceObj is IArgsInstantiable<TArg0> argsInstantiable)
                argsInstantiable.Initialize(arg0);

            return instanceObj;
        }

        /// <summary>)
        /// Instantiates a Object that derives from IArgsInstantiable with 1 parameters and calls the initialize function
        /// </summary>
        public static T Instantiate<T, TArg0>(T original, Vector3 position, Quaternion rotation, Transform parent, TArg0 arg0) where T : Object, IArgsInstantiable<TArg0>
        {
            var instanceObj = Object.Instantiate(original, position, rotation, parent);

            if (instanceObj is IArgsInstantiable<TArg0> argsInstantiable)
                argsInstantiable.Initialize(arg0);

            return instanceObj;
        }

        /// <summary>)
        /// Instantiates a Object that derives from IArgsInstantiable with 2 parameters and calls the initialize function
        /// </summary>
        public static T Instantiate<T, TArg0, TArg1>(T original, TArg0 arg0, TArg1 arg1) where T : Object, IArgsInstantiable<TArg0, TArg1>
        {
            var instanceObj = Object.Instantiate(original);

            if (instanceObj is IArgsInstantiable<TArg0, TArg1> argsInstantiable)
                argsInstantiable.Initialize(arg0, arg1);

            return instanceObj;
        }

        /// <summary>)
        /// Instantiates a Object that derives from IArgsInstantiable with 2 parameters and calls the initialize function
        /// </summary>
        public static T Instantiate<T, TArg0, TArg1>(T original, Transform parent, TArg0 arg0, TArg1 arg1) where T : Object, IArgsInstantiable<TArg0, TArg1>
        {
            var instanceObj = Object.Instantiate(original, parent);

            if (instanceObj is IArgsInstantiable<TArg0, TArg1> argsInstantiable)
                argsInstantiable.Initialize(arg0, arg1);

            return instanceObj;
        }

        /// <summary>)
        /// Instantiates a Object that derives from IArgsInstantiable with 2 parameters and calls the initialize function
        /// </summary>
        public static T Instantiate<T, TArg0, TArg1>(T original, Vector3 position, Quaternion rotation, TArg0 arg0, TArg1 arg1) where T : Object, IArgsInstantiable<TArg0, TArg1>
        {
            var instanceObj = Object.Instantiate(original, position, rotation);

            if (instanceObj is IArgsInstantiable<TArg0, TArg1> argsInstantiable)
                argsInstantiable.Initialize(arg0, arg1);

            return instanceObj;
        }

        /// <summary>)
        /// Instantiates a Object that derives from IArgsInstantiable with 2 parameters and calls the initialize function
        /// </summary>
        public static T Instantiate<T, TArg0, TArg1>(T original, Vector3 position, Quaternion rotation, Transform parent, TArg0 arg0, TArg1 arg1) where T : Object, IArgsInstantiable<TArg0, TArg1>
        {
            var instanceObj = Object.Instantiate(original, position, rotation, parent);

            if (instanceObj is IArgsInstantiable<TArg0, TArg1> argsInstantiable)
                argsInstantiable.Initialize(arg0, arg1);

            return instanceObj;
        }

        /// <summary>)
        /// Instantiates a Object that derives from IArgsInstantiable with 3 parameters and calls the initialize function
        /// </summary>
        public static T Instantiate<T, TArg0, TArg1, TArg2>(T original, TArg0 arg0, TArg1 arg1, TArg2 arg2) where T : Object, IArgsInstantiable<TArg0, TArg1, TArg2>
        {
            var instanceObj = Object.Instantiate(original);

            if (instanceObj is IArgsInstantiable<TArg0, TArg1, TArg2> argsInstantiable)
                argsInstantiable.Initialize(arg0, arg1, arg2);

            return instanceObj;
        }

        /// <summary>)
        /// Instantiates a Object that derives from IArgsInstantiable with 3 parameters and calls the initialize function
        /// </summary>
        public static T Instantiate<T, TArg0, TArg1, TArg2>(T original, Transform parent, TArg0 arg0, TArg1 arg1, TArg2 arg2) where T : Object, IArgsInstantiable<TArg0, TArg1, TArg2>
        {
            var instanceObj = Object.Instantiate(original, parent);

            if (instanceObj is IArgsInstantiable<TArg0, TArg1, TArg2> argsInstantiable)
                argsInstantiable.Initialize(arg0, arg1, arg2);

            return instanceObj;
        }

        /// <summary>)
        /// Instantiates a Object that derives from IArgsInstantiable with 3 parameters and calls the initialize function
        /// </summary>
        public static T Instantiate<T, TArg0, TArg1, TArg2>(T original, Vector3 position, Quaternion rotation, TArg0 arg0, TArg1 arg1, TArg2 arg2) where T : Object, IArgsInstantiable<TArg0, TArg1, TArg2>
        {
            var instanceObj = Object.Instantiate(original, position, rotation);

            if (instanceObj is IArgsInstantiable<TArg0, TArg1, TArg2> argsInstantiable)
                argsInstantiable.Initialize(arg0, arg1, arg2);

            return instanceObj;
        }

        /// <summary>)
        /// Instantiates a Object that derives from IArgsInstantiable with 3 parameters and calls the initialize function
        /// </summary>
        public static T Instantiate<T, TArg0, TArg1, TArg2>(T original, Vector3 position, Quaternion rotation, Transform parent, TArg0 arg0, TArg1 arg1, TArg2 arg2) where T : Object, IArgsInstantiable<TArg0, TArg1, TArg2>
        {
            var instanceObj = Object.Instantiate(original, position, rotation, parent);

            if (instanceObj is IArgsInstantiable<TArg0, TArg1, TArg2> argsInstantiable)
                argsInstantiable.Initialize(arg0, arg1, arg2);

            return instanceObj;
        }

        /// <summary>)
        /// Instantiates a Object that derives from IArgsInstantiable with 4 parameters and calls the initialize function
        /// </summary>
        public static T Instantiate<T, TArg0, TArg1, TArg2, TArg3>(T original, TArg0 arg0, TArg1 arg1, TArg2 arg2, TArg3 arg3) where T : Object, IArgsInstantiable<TArg0, TArg1, TArg2, TArg3>
        {
            var instanceObj = Object.Instantiate(original);

            if (instanceObj is IArgsInstantiable<TArg0, TArg1, TArg2, TArg3> argsInstantiable)
                argsInstantiable.Initialize(arg0, arg1, arg2, arg3);

            return instanceObj;
        }

        /// <summary>)
        /// Instantiates a Object that derives from IArgsInstantiable with 4 parameters and calls the initialize function
        /// </summary>
        public static T Instantiate<T, TArg0, TArg1, TArg2, TArg3>(T original, Transform parent, TArg0 arg0, TArg1 arg1, TArg2 arg2, TArg3 arg3) where T : Object, IArgsInstantiable<TArg0, TArg1, TArg2, TArg3>
        {
            var instanceObj = Object.Instantiate(original, parent);

            if (instanceObj is IArgsInstantiable<TArg0, TArg1, TArg2, TArg3> argsInstantiable)
                argsInstantiable.Initialize(arg0, arg1, arg2, arg3);

            return instanceObj;
        }

        /// <summary>)
        /// Instantiates a Object that derives from IArgsInstantiable with 4 parameters and calls the initialize function
        /// </summary>
        public static T Instantiate<T, TArg0, TArg1, TArg2, TArg3>(T original, Vector3 position, Quaternion rotation, TArg0 arg0, TArg1 arg1, TArg2 arg2, TArg3 arg3) where T : Object, IArgsInstantiable<TArg0, TArg1, TArg2, TArg3>
        {
            var instanceObj = Object.Instantiate(original, position, rotation);

            if (instanceObj is IArgsInstantiable<TArg0, TArg1, TArg2, TArg3> argsInstantiable)
                argsInstantiable.Initialize(arg0, arg1, arg2, arg3);

            return instanceObj;
        }

        /// <summary>)
        /// Instantiates a Object that derives from IArgsInstantiable with 4 parameters and calls the initialize function
        /// </summary>
        public static T Instantiate<T, TArg0, TArg1, TArg2, TArg3>(T original, Vector3 position, Quaternion rotation, Transform parent, TArg0 arg0, TArg1 arg1, TArg2 arg2, TArg3 arg3) where T : Object, IArgsInstantiable<TArg0, TArg1, TArg2, TArg3>
        {
            var instanceObj = Object.Instantiate(original, position, rotation, parent);

            if (instanceObj is IArgsInstantiable<TArg0, TArg1, TArg2, TArg3> argsInstantiable)
                argsInstantiable.Initialize(arg0, arg1, arg2, arg3);

            return instanceObj;
        }

        /// <summary>)
        /// Instantiates a Object that derives from IArgsInstantiable with 5 parameters and calls the initialize function
        /// </summary>
        public static T Instantiate<T, TArg0, TArg1, TArg2, TArg3, TArg4>(T original, TArg0 arg0, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4) where T : Object, IArgsInstantiable<TArg0, TArg1, TArg2, TArg3, TArg4>
        {
            var instanceObj = Object.Instantiate(original);

            if (instanceObj is IArgsInstantiable<TArg0, TArg1, TArg2, TArg3, TArg4> argsInstantiable)
                argsInstantiable.Initialize(arg0, arg1, arg2, arg3, arg4);

            return instanceObj;
        }

        /// <summary>)
        /// Instantiates a Object that derives from IArgsInstantiable with 5 parameters and calls the initialize function
        /// </summary>
        public static T Instantiate<T, TArg0, TArg1, TArg2, TArg3, TArg4>(T original, Transform parent, TArg0 arg0, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4) where T : Object, IArgsInstantiable<TArg0, TArg1, TArg2, TArg3, TArg4>
        {
            var instanceObj = Object.Instantiate(original, parent);

            if (instanceObj is IArgsInstantiable<TArg0, TArg1, TArg2, TArg3, TArg4> argsInstantiable)
                argsInstantiable.Initialize(arg0, arg1, arg2, arg3, arg4);

            return instanceObj;
        }

        /// <summary>)
        /// Instantiates a Object that derives from IArgsInstantiable with 5 parameters and calls the initialize function
        /// </summary>
        public static T Instantiate<T, TArg0, TArg1, TArg2, TArg3, TArg4>(T original, Vector3 position, Quaternion rotation, TArg0 arg0, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4) where T : Object, IArgsInstantiable<TArg0, TArg1, TArg2, TArg3, TArg4>
        {
            var instanceObj = Object.Instantiate(original, position, rotation);

            if (instanceObj is IArgsInstantiable<TArg0, TArg1, TArg2, TArg3, TArg4> argsInstantiable)
                argsInstantiable.Initialize(arg0, arg1, arg2, arg3, arg4);

            return instanceObj;
        }

        /// <summary>)
        /// Instantiates a Object that derives from IArgsInstantiable with 5 parameters and calls the initialize function
        /// </summary>
        public static T Instantiate<T, TArg0, TArg1, TArg2, TArg3, TArg4>(T original, Vector3 position, Quaternion rotation, Transform parent, TArg0 arg0, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4) where T : Object, IArgsInstantiable<TArg0, TArg1, TArg2, TArg3, TArg4>
        {
            var instanceObj = Object.Instantiate(original, position, rotation, parent);

            if (instanceObj is IArgsInstantiable<TArg0, TArg1, TArg2, TArg3, TArg4> argsInstantiable)
                argsInstantiable.Initialize(arg0, arg1, arg2, arg3, arg4);

            return instanceObj;
        }

        /// <summary>)
        /// Instantiates a Object that derives from IArgsInstantiable with 6 parameters and calls the initialize function
        /// </summary>
        public static T Instantiate<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5>(T original, TArg0 arg0, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5) where T : Object, IArgsInstantiable<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5>
        {
            var instanceObj = Object.Instantiate(original);

            if (instanceObj is IArgsInstantiable<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5> argsInstantiable)
                argsInstantiable.Initialize(arg0, arg1, arg2, arg3, arg4, arg5);

            return instanceObj;
        }

        /// <summary>)
        /// Instantiates a Object that derives from IArgsInstantiable with 6 parameters and calls the initialize function
        /// </summary>
        public static T Instantiate<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5>(T original, Transform parent, TArg0 arg0, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5) where T : Object, IArgsInstantiable<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5>
        {
            var instanceObj = Object.Instantiate(original, parent);

            if (instanceObj is IArgsInstantiable<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5> argsInstantiable)
                argsInstantiable.Initialize(arg0, arg1, arg2, arg3, arg4, arg5);

            return instanceObj;
        }

        /// <summary>)
        /// Instantiates a Object that derives from IArgsInstantiable with 6 parameters and calls the initialize function
        /// </summary>
        public static T Instantiate<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5>(T original, Vector3 position, Quaternion rotation, TArg0 arg0, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5) where T : Object, IArgsInstantiable<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5>
        {
            var instanceObj = Object.Instantiate(original, position, rotation);

            if (instanceObj is IArgsInstantiable<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5> argsInstantiable)
                argsInstantiable.Initialize(arg0, arg1, arg2, arg3, arg4, arg5);

            return instanceObj;
        }

        /// <summary>)
        /// Instantiates a Object that derives from IArgsInstantiable with 6 parameters and calls the initialize function
        /// </summary>
        public static T Instantiate<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5>(T original, Vector3 position, Quaternion rotation, Transform parent, TArg0 arg0, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5) where T : Object, IArgsInstantiable<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5>
        {
            var instanceObj = Object.Instantiate(original, position, rotation, parent);

            if (instanceObj is IArgsInstantiable<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5> argsInstantiable)
                argsInstantiable.Initialize(arg0, arg1, arg2, arg3, arg4, arg5);

            return instanceObj;
        }

        /// <summary>)
        /// Instantiates a Object that derives from IArgsInstantiable with 7 parameters and calls the initialize function
        /// </summary>
        public static T Instantiate<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6>(T original, TArg0 arg0, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6) where T : Object, IArgsInstantiable<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6>
        {
            var instanceObj = Object.Instantiate(original);

            if (instanceObj is IArgsInstantiable<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6> argsInstantiable)
                argsInstantiable.Initialize(arg0, arg1, arg2, arg3, arg4, arg5, arg6);

            return instanceObj;
        }

        /// <summary>)
        /// Instantiates a Object that derives from IArgsInstantiable with 7 parameters and calls the initialize function
        /// </summary>
        public static T Instantiate<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6>(T original, Transform parent, TArg0 arg0, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6) where T : Object, IArgsInstantiable<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6>
        {
            var instanceObj = Object.Instantiate(original, parent);

            if (instanceObj is IArgsInstantiable<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6> argsInstantiable)
                argsInstantiable.Initialize(arg0, arg1, arg2, arg3, arg4, arg5, arg6);

            return instanceObj;
        }

        /// <summary>)
        /// Instantiates a Object that derives from IArgsInstantiable with 7 parameters and calls the initialize function
        /// </summary>
        public static T Instantiate<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6>(T original, Vector3 position, Quaternion rotation, TArg0 arg0, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6) where T : Object, IArgsInstantiable<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6>
        {
            var instanceObj = Object.Instantiate(original, position, rotation);

            if (instanceObj is IArgsInstantiable<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6> argsInstantiable)
                argsInstantiable.Initialize(arg0, arg1, arg2, arg3, arg4, arg5, arg6);

            return instanceObj;
        }

        /// <summary>)
        /// Instantiates a Object that derives from IArgsInstantiable with 7 parameters and calls the initialize function
        /// </summary>
        public static T Instantiate<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6>(T original, Vector3 position, Quaternion rotation, Transform parent, TArg0 arg0, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6) where T : Object, IArgsInstantiable<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6>
        {
            var instanceObj = Object.Instantiate(original, position, rotation, parent);

            if (instanceObj is IArgsInstantiable<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6> argsInstantiable)
                argsInstantiable.Initialize(arg0, arg1, arg2, arg3, arg4, arg5, arg6);

            return instanceObj;
        }

        /// <summary>)
        /// Instantiates a Object that derives from IArgsInstantiable with 8 parameters and calls the initialize function
        /// </summary>
        public static T Instantiate<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7>(T original, TArg0 arg0, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7) where T : Object, IArgsInstantiable<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7>
        {
            var instanceObj = Object.Instantiate(original);

            if (instanceObj is IArgsInstantiable<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7> argsInstantiable)
                argsInstantiable.Initialize(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);

            return instanceObj;
        }

        /// <summary>)
        /// Instantiates a Object that derives from IArgsInstantiable with 8 parameters and calls the initialize function
        /// </summary>
        public static T Instantiate<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7>(T original, Transform parent, TArg0 arg0, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7) where T : Object, IArgsInstantiable<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7>
        {
            var instanceObj = Object.Instantiate(original, parent);

            if (instanceObj is IArgsInstantiable<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7> argsInstantiable)
                argsInstantiable.Initialize(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);

            return instanceObj;
        }

        /// <summary>)
        /// Instantiates a Object that derives from IArgsInstantiable with 8 parameters and calls the initialize function
        /// </summary>
        public static T Instantiate<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7>(T original, Vector3 position, Quaternion rotation, TArg0 arg0, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7) where T : Object, IArgsInstantiable<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7>
        {
            var instanceObj = Object.Instantiate(original, position, rotation);

            if (instanceObj is IArgsInstantiable<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7> argsInstantiable)
                argsInstantiable.Initialize(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);

            return instanceObj;
        }

        /// <summary>)
        /// Instantiates a Object that derives from IArgsInstantiable with 8 parameters and calls the initialize function
        /// </summary>
        public static T Instantiate<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7>(T original, Vector3 position, Quaternion rotation, Transform parent, TArg0 arg0, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7) where T : Object, IArgsInstantiable<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7>
        {
            var instanceObj = Object.Instantiate(original, position, rotation, parent);

            if (instanceObj is IArgsInstantiable<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7> argsInstantiable)
                argsInstantiable.Initialize(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);

            return instanceObj;
        }

        /// <summary>)
        /// Instantiates a Object that derives from IArgsInstantiable with 9 parameters and calls the initialize function
        /// </summary>
        public static T Instantiate<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8>(T original, TArg0 arg0, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7, TArg8 arg8) where T : Object, IArgsInstantiable<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8>
        {
            var instanceObj = Object.Instantiate(original);

            if (instanceObj is IArgsInstantiable<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8> argsInstantiable)
                argsInstantiable.Initialize(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);

            return instanceObj;
        }

        /// <summary>)
        /// Instantiates a Object that derives from IArgsInstantiable with 9 parameters and calls the initialize function
        /// </summary>
        public static T Instantiate<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8>(T original, Transform parent, TArg0 arg0, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7, TArg8 arg8) where T : Object, IArgsInstantiable<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8>
        {
            var instanceObj = Object.Instantiate(original, parent);

            if (instanceObj is IArgsInstantiable<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8> argsInstantiable)
                argsInstantiable.Initialize(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);

            return instanceObj;
        }

        /// <summary>)
        /// Instantiates a Object that derives from IArgsInstantiable with 9 parameters and calls the initialize function
        /// </summary>
        public static T Instantiate<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8>(T original, Vector3 position, Quaternion rotation, TArg0 arg0, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7, TArg8 arg8) where T : Object, IArgsInstantiable<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8>
        {
            var instanceObj = Object.Instantiate(original, position, rotation);

            if (instanceObj is IArgsInstantiable<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8> argsInstantiable)
                argsInstantiable.Initialize(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);

            return instanceObj;
        }

        /// <summary>)
        /// Instantiates a Object that derives from IArgsInstantiable with 9 parameters and calls the initialize function
        /// </summary>
        public static T Instantiate<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8>(T original, Vector3 position, Quaternion rotation, Transform parent, TArg0 arg0, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7, TArg8 arg8) where T : Object, IArgsInstantiable<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8>
        {
            var instanceObj = Object.Instantiate(original, position, rotation, parent);

            if (instanceObj is IArgsInstantiable<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8> argsInstantiable)
                argsInstantiable.Initialize(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);

            return instanceObj;
        }

        /// <summary>)
        /// Instantiates a Object that derives from IArgsInstantiable with 10 parameters and calls the initialize function
        /// </summary>
        public static T Instantiate<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9>(T original, TArg0 arg0, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7, TArg8 arg8, TArg9 arg9) where T : Object, IArgsInstantiable<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9>
        {
            var instanceObj = Object.Instantiate(original);

            if (instanceObj is IArgsInstantiable<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9> argsInstantiable)
                argsInstantiable.Initialize(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);

            return instanceObj;
        }

        /// <summary>)
        /// Instantiates a Object that derives from IArgsInstantiable with 10 parameters and calls the initialize function
        /// </summary>
        public static T Instantiate<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9>(T original, Transform parent, TArg0 arg0, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7, TArg8 arg8, TArg9 arg9) where T : Object, IArgsInstantiable<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9>
        {
            var instanceObj = Object.Instantiate(original, parent);

            if (instanceObj is IArgsInstantiable<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9> argsInstantiable)
                argsInstantiable.Initialize(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);

            return instanceObj;
        }

        /// <summary>)
        /// Instantiates a Object that derives from IArgsInstantiable with 10 parameters and calls the initialize function
        /// </summary>
        public static T Instantiate<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9>(T original, Vector3 position, Quaternion rotation, TArg0 arg0, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7, TArg8 arg8, TArg9 arg9) where T : Object, IArgsInstantiable<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9>
        {
            var instanceObj = Object.Instantiate(original, position, rotation);

            if (instanceObj is IArgsInstantiable<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9> argsInstantiable)
                argsInstantiable.Initialize(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);

            return instanceObj;
        }

        /// <summary>)
        /// Instantiates a Object that derives from IArgsInstantiable with 10 parameters and calls the initialize function
        /// </summary>
        public static T Instantiate<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9>(T original, Vector3 position, Quaternion rotation, Transform parent, TArg0 arg0, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7, TArg8 arg8, TArg9 arg9) where T : Object, IArgsInstantiable<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9>
        {
            var instanceObj = Object.Instantiate(original, position, rotation, parent);

            if (instanceObj is IArgsInstantiable<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9> argsInstantiable)
                argsInstantiable.Initialize(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);

            return instanceObj;
        }

    }
}
